### ISSUE TITLE
Implement Debug for Framebuffer

### ISSUE THREAD

**Issue by CodeGradox** [Roysten/rust-framebuffer#4]
Is there a reason for the Framebuffer struct to not implement the `Debug` trait? I want to store a `Framebuffer` inside a struct which implements `Debug`, but this results in an error. I don't think I can implement this trait on `Framebuffer` in my own project.

I checked the `File` and `Mmap` structs which `Framebuffer` uses and they both implement `Debug`, so there should not be an issue to do the same for `Framebuffer`, right?

**Comment by Roysten** [comment]
There is no reason, I simply forgot :) Thanks for the report. It will be available in version 0.1.6, which I will publish right away.
