### ISSUE TITLE
Starfield demo could crash with divide by zero

### ISSUE THREAD

**Issue by earthspike** [Roysten/rust-framebuffer#8]
[Line 87 of starfield/main.rs](https://github.com/Roysten/rust-framebuffer/blob/a71bad6d38b622e6757f02cdf990d4f7d66f5fe2/examples/starfield/main.rs#L87) sets `self.x` to a random float between `-wh` and `wh` which could include the value 0. [Line 89](https://github.com/Roysten/rust-framebuffer/blob/a71bad6d38b622e6757f02cdf990d4f7d66f5fe2/examples/starfield/main.rs#L89) divides `self.b` by that number, which could result in a divide by zero.

**Comment by Roysten** [comment]
Fixed, thank you.
